schema:
- name: immortalize
  path: .
  commands:
    build:
      status: true
      args:
        - -o
        - work/immortalize
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
