#!/bin/bash -eu

# https://stackoverflow.com/questions/9256644
trap_with_arg() {
  func="$1" ; shift
  for sig ; do
    # shellcheck disable=SC2064
    trap "$func $sig" "$sig"
  done
}

func_trap() {
  >&2 echo "Trapped: $1"
  exit 1
}

trap_with_arg func_trap INT TERM EXIT

for i in {1..8}; do
  sleep 0.5
  >&2 echo "$i / 8"
done

exit 1
